#!/bin/bash

SHELL=/bin/bash
PATH=/root/.nodebrew/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

*/2 * * * * root /bin/bash /home/atmark/KuiEdgeMachine/check_flashair.sh >> /var/log/check_flashair.log 2>&1
