#!/bin/bash

wait_els_ready(){
	for ((i=0; i < 60; i++)); do
		ping -c 3 192.168.15.1
		if [ $? -eq 0 ]; then
			return 0;
		fi
		sleep 1
	done
	echo "error: ELS31-J Not Ready"
	exit 1;
}

service connection-recover stop
service ModemManager stop
service NetworkManager restart
wait_els_ready

./els31-firewall-change
